pub const FIRST_RANK: u64 = 255;
pub const SECOND_RANK: u64 = 255 << 8;
pub const THIRD_RANK: u64 = 255 << 16;
pub const FOURTH_RANK: u64 = 255 << 24;
pub const FIFTH_RANK: u64 = 255 << 32;
pub const SIXTH_RANK: u64 = 255 << 40;
pub const SEVENTH_RANK: u64 = 255 << 48;
pub const EIGHTH_RANK: u64 = 255 << 56;

pub const A_FILE: u64 = 1_u64 + (1_u64 << 8) | (1_u64 << 16) | (1_u64 << 24) | (1_u64 << 32) | (1_u64 << 40) | (1_u64 << 48) | (1_u64 << 56);
pub const B_FILE: u64 = A_FILE << 1;
pub const C_FILE: u64 = A_FILE << 2;
pub const D_FILE: u64 = A_FILE << 3;
pub const E_FILE: u64 = A_FILE << 4;
pub const F_FILE: u64 = A_FILE << 5;
pub const G_FILE: u64 = A_FILE << 6;
pub const H_FILE: u64 = A_FILE << 7;

pub const JESUS: [u64; 64] = [
    A_FILE | FIRST_RANK, B_FILE | FIRST_RANK, C_FILE | FIRST_RANK, D_FILE | FIRST_RANK, E_FILE | FIRST_RANK, F_FILE | FIRST_RANK, G_FILE | FIRST_RANK, H_FILE | FIRST_RANK,
    A_FILE | SECOND_RANK, B_FILE | SECOND_RANK, C_FILE | SECOND_RANK, D_FILE | SECOND_RANK, E_FILE | SECOND_RANK, F_FILE | SECOND_RANK, G_FILE | SECOND_RANK, H_FILE | SECOND_RANK,
    A_FILE | THIRD_RANK, B_FILE | THIRD_RANK, C_FILE | THIRD_RANK, D_FILE | THIRD_RANK, E_FILE | THIRD_RANK, F_FILE | THIRD_RANK, G_FILE | THIRD_RANK, H_FILE | THIRD_RANK,
    A_FILE | FOURTH_RANK, B_FILE | FOURTH_RANK, C_FILE | FOURTH_RANK, D_FILE | FOURTH_RANK, E_FILE | FOURTH_RANK, F_FILE | FOURTH_RANK, G_FILE | FOURTH_RANK, H_FILE | FOURTH_RANK,
    A_FILE | FIFTH_RANK, B_FILE | FIFTH_RANK, C_FILE | FIFTH_RANK, D_FILE | FIFTH_RANK, E_FILE | FIFTH_RANK, F_FILE | FIFTH_RANK, G_FILE | FIFTH_RANK, H_FILE | FIFTH_RANK,
    A_FILE | SIXTH_RANK, B_FILE | SIXTH_RANK, C_FILE | SIXTH_RANK, D_FILE | SIXTH_RANK, E_FILE | SIXTH_RANK, F_FILE | SIXTH_RANK, G_FILE | SIXTH_RANK, H_FILE | SIXTH_RANK,
    A_FILE | SEVENTH_RANK, B_FILE | SEVENTH_RANK, C_FILE | SEVENTH_RANK, D_FILE | SEVENTH_RANK, E_FILE | SEVENTH_RANK, F_FILE | SEVENTH_RANK, G_FILE | SEVENTH_RANK, H_FILE | SEVENTH_RANK,
    A_FILE | EIGHTH_RANK, B_FILE | EIGHTH_RANK, C_FILE | EIGHTH_RANK, D_FILE | EIGHTH_RANK, E_FILE | EIGHTH_RANK, F_FILE | EIGHTH_RANK, G_FILE | EIGHTH_RANK, H_FILE | EIGHTH_RANK,
];