[package]
name = "chess-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
rand = "0.8.5"
lazy_mut = "0.1.0"
once_cell = "1.18.0"
lazy_static = "1.4.0"